refacturedRuttonSettingsRefactoring
Cost-Effective-Software-Project-11/gp5 pull request #17
Opened 2024-05-25 07:45 UTC by Jorjo77

2024-05-25 13:54 UTC, HristoPetkov94 requested changes

2024-05-25 13:54 UTC, HristoPetkov94 commented on lib/screens/home/home_screen.dart
> +  class ButtonSettings {
this is never used, delete it or is there reason why we need it ?

2024-05-26 04:48 UTC, Jorjo77 commented on lib/screens/home/home_screen.dart
> +  class ButtonSettings {
OK, I've confused refactoring ButtonSettings.

2024-05-26 04:56 UTC, Jorjo77 commented
I've fix it: https://github.com/Cost-Effective-Software-Project-11/gp5/pull/17/commits/30aa6c8b45ce09b623457e024622680f6a81f46c

2024-05-26 04:58 UTC, Jorjo77 commented
Do I need to make new pool request or when approve this one I'll merge?

2024-05-26 09:52 UTC, HristoPetkov94 approved these changes

2024-05-27 10:25 UTC, Peshp approved these changes

2024-05-27 18:15 UTC, merged