buildContextExtentionWithUsageInHomeScreenCreated
Cost-Effective-Software-Project-11/gp5 pull request #18
Opened 2024-05-27 10:17 UTC by Jorjo77

I'm not sure if it is the right usage.

2024-05-27 16:16 UTC, HristoPetkov94 requested changes

2024-05-27 16:16 UTC, HristoPetkov94 commented on lib/extensions/build_context_extensions.dart
> +    return MediaQuery.of(this).size.width * (percentage / 100);
MediaQuery.of(this).size.width to be extracted into private class variable

2024-05-27 16:16 UTC, HristoPetkov94 commented on lib/extensions/build_context_extensions.dart
> +    return MediaQuery.of(this).size.height * (percentage / 100);
(percentage / 100) this to be separate method  example _getDecimalPercentage(percent)

2024-05-27 16:16 UTC, HristoPetkov94 commented on lib/extensions/build_context_extensions.dart
> +  double heightPercentage(double percentage) {
method name to be setHeight

2024-05-27 16:16 UTC, HristoPetkov94 commented on lib/extensions/build_context_extensions.dart
> +    assert(percentage >= 0 && percentage <= 100);
test what happens if you add number out of the scope 0 and 100

2024-05-27 16:16 UTC, HristoPetkov94 commented on lib/extensions/build_context_extensions.dart
> +   // Convert width percentage to pixel value
redundant comment

2024-05-28 18:26 UTC, Jorjo77 commented
I'm not sure, but maby waiting for approvement...

2024-05-29 16:51 UTC, HristoPetkov94 approved these changes

2024-05-29 16:53 UTC, merged