Implement create trials screen
Cost-Effective-Software-Project-11/gp5 pull request #25
Opened 2024-05-31 18:46 UTC by Peshp

2024-06-01 15:02 UTC, HristoPetkov94 requested changes

2024-06-02 07:42 UTC, Peshp commented on lib/screens/create_trials/create_trials_screen.dart
> +import 'dart:html';
I've removed that import.

2024-06-02 07:43 UTC, Peshp commented on lib/screens/create_trials/create_trials_screen.dart
> +          Expanded(
I've removed every expanded widget.

2024-06-02 07:43 UTC, Peshp commented on pubspec.yaml
> +  syncfusion_flutter_pdf: ^25.2.6
I've removed escort to pdf button, because is not needed for this task.

2024-06-06 20:11 UTC, HristoPetkov94 commented on pubspec.yaml
> +  syncfusion_flutter_pdf: ^25.2.6
remove the dependency aswell

2024-06-06 20:11 UTC, HristoPetkov94 approved these changes

2024-06-07 15:56 UTC, merged