bugfix supported languages
Cost-Effective-Software-Project-11/gp5 pull request #50
Opened 2024-06-27 19:55 UTC by kvinceto

2024-06-28 20:48 UTC, HristoPetkov94 requested changes

2024-06-28 20:48 UTC, HristoPetkov94 commented on lib/screens/settings/language_dropdown_button.dart
> +    final supportedLanguages = Language.supportedLanguages(context);
The idea is to move supportedLanguages outside of the build method. Since this is a stateful widget, the build method is called on each state change, causing supportedLanguages to be rebuilt unnecessarily.

2024-06-28 20:48 UTC, HristoPetkov94 commented on lib/utils/supported_language_model.dart
> +    final localizations = AppLocale.of(context)!;
You don't need context; you can hardcode the labels for the languages as text: Български, English, Dutch.

2024-07-04 00:49 UTC, kvinceto commented on lib/utils/supported_language_model.dart
> +    final localizations = AppLocale.of(context)!;
Cannot be hardcoded due to dynamic name change

2024-07-04 00:49 UTC, kvinceto commented on lib/screens/settings/language_dropdown_button.dart
> +    final supportedLanguages = Language.supportedLanguages(context);
Context has to be given to the method

2024-07-04 13:09 UTC, HristoPetkov94 commented on lib/screens/settings/language_dropdown_button.dart
> +    final supportedLanguages = Language.supportedLanguages(context);
yes, what for? you dont need it. extract it and do it without context

2024-07-04 13:10 UTC, HristoPetkov94 commented on lib/screens/settings/language_dropdown_button.dart
> +    final supportedLanguages = Language.supportedLanguages(context);
just dont use localization for those 3 strings

2024-07-04 15:38 UTC, merged