Create home screen
Cost-Effective-Software-Project-11/gp5 pull request #68
Opened 2024-08-13 15:12 UTC by VictorAgovski

2024-08-13 15:43 UTC, VictorAgovski commented
1) profile picture is logout button
2) The exception occurs when switching between doctors and institutions in the home screen

2024-08-14 12:47 UTC, HristoPetkov94 commented
That happened after going to institutions and the b back to doctors

![image](https://github.com/user-attachments/assets/2aeacd40-bc22-4e41-af02-b6723691f2b5)

2024-08-14 12:48 UTC, HristoPetkov94 commented
limit it to 4-5 and update the margins paddings to look better 

![image](https://github.com/user-attachments/assets/9f8e9cd3-2045-422b-8910-df7d51a033e5)

2024-08-14 12:49 UTC, HristoPetkov94 commented
fix the error
![image](https://github.com/user-attachments/assets/cc01fddf-6d65-4910-bae1-f94aa5ee575e)

2024-08-14 12:51 UTC, HristoPetkov94 commented
The options in the chips should be only from the existing options in the result list

2024-08-14 13:03 UTC, HristoPetkov94 requested changes

2024-08-14 13:16 UTC, HristoPetkov94 commented on lib/screens/home/home_screen2.dart
> +    var snapshot = await FirebaseFirestore.instance.collection('institutions').get();
this should be in repository, called from bloc, used here

2024-08-25 11:48 UTC, VictorAgovski commented
> limit it to 4-5 and update the margins paddings to look better
> 
> ![image](https://private-user-images.githubusercontent.com/26842648/357817147-9f8e9cd3-2045-422b-8910-df7d51a033e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODY1NDIsIm5iZiI6MTcyNDU4NjI0MiwicGF0aCI6Ii8yNjg0MjY0OC8zNTc4MTcxNDctOWY4ZTljZDMtMjA0NS00MjJiLTg5MTAtZGY3ZDUxYTAzM2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDExNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGU2YTMxY2ZlNDgwZTFkZjdlNWNlZDM5MzdjNmVlZWY2ZjUxNmFmYWUyNzQ1N2ZjY2E3YTM0N2MyY2NjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wQNQhU1-9Cqt1aW1O-SlCXDsj999TWdoTAXWiZdeFos)

I haven't changed the UI yet

2024-08-25 11:51 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +class HomeScreen2 extends StatefulWidget {
it's still that way, i haven't deleted the home_screen.dart yet

2024-08-25 11:52 UTC, VictorAgovski commented on lib/screens/home/home_screen.dart
>  class HomeScreen extends StatelessWidget {
this screen is not used (home_screen.dart)

2024-08-25 11:52 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +  TextEditingController searchController = TextEditingController();
this is done

2024-08-25 12:11 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +    var snapshot = await FirebaseFirestore.instance.collection('institutions').get();
this is done

2024-08-25 12:11 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +                    content: const Text("You can set your filters or clear all existing ones."),
not done yet

2024-08-25 12:12 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +          return Text('Something went wrong: ${snapshot.error}');
not done yet

2024-08-25 12:12 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +  Widget buildBottomNavigationBar(BuildContext context, AuthenticationRepository authRepo) {
not done yet

2024-08-25 12:12 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +    var query = FirebaseFirestore.instance.collection('institutions');
it is done

2024-08-25 12:12 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +    setState(() {
it is done

2024-08-25 12:26 UTC, VictorAgovski commented on lib/screens/home/home_screen2.dart
> +    var snapshot = await FirebaseFirestore.instance.collection('institutions').get();
in home_bloc.dart some methods use FutureBuilder, because otherwise no data is fetched from the database and I am not sure why

2024-08-25 13:17 UTC, HristoPetkov94 commented
1. AppBAr
2. Background image
3. Create Input field with the icons (no business logic)
4. Create row of filter buttons. with option selected filters to be displayed under them.
5. List doctors
6. List institutions

{
  "email": "primer@primer.bg",
  "names": "Иван Иванов",
  "password": "сигурнаПарола123",
  "phone": "+359888123456",
  "type": "doctor",
  "speciality": "Кардиология",
  "institution": "Градска болница",
  "city": "София"
}

events:
abstract class HomeEvent {}

class LoadInitialData extends HomeEvent {}

class UpdateSearchText extends HomeEvent {
  final String query;
  UpdateSearchText(this.query);
}

class ToggleSpecialization extends HomeEvent {
  final String specialization;
  ToggleSpecialization(this.specialization);
}

class ToggleCity extends HomeEvent {
  final String city;
  ToggleCity(this.city);
}

class ClearFilters extends HomeEvent {}

State
class HomeState {
  final List<Doctor> doctors;
  final List<Institution> institutions;
  final List<String> specializations;
  final List<String> cities;
  final List<String> selectedSpecializations;
  final List<String> selectedCities;
  final String searchQuery;

  HomeState({
    this.doctors = const [],
    this.institutions = const [],
    this.specializations = const [],
    this.cities = const [],
    this.selectedSpecializations = const [],
    this.selectedCities = const [],
    this.searchQuery = '',
  });

  HomeState copyWith({
    List<Doctor>? doctors,
    List<Institution>? institutions,
    List<String>? specializations,
    List<String>? cities,
    List<String>? selectedSpecializations,
    List<String>? selectedCities,
    String? searchQuery,
  }) {
    return HomeState(
      doctors: doctors ?? this.doctors,
      institutions: institutions ?? this.institutions,
      specializations: specializations ?? this.specializations,
      cities: cities ?? this.cities,
      selectedSpecializations: selectedSpecializations ?? this.selectedSpecializations,
      selectedCities: selectedCities ?? this.selectedCities,
      searchQuery: searchQuery ?? this.searchQuery,
    );
  }
}

class LoadingState extends HomeState {
  @override
  List<Object> get props=> [];
}

2024-08-29 16:33 UTC, HristoPetkov94 commented
![image](https://github.com/user-attachments/assets/ebbba0cd-9ffe-47a2-ab5e-cd386b3d75f0)

When no matching result should be text not progress indicator

2024-08-29 16:37 UTC, HristoPetkov94 commented
![image](https://github.com/user-attachments/assets/63d55ff2-7c47-40b8-bfef-08eb70cdfc22)

2024-08-29 16:39 UTC, HristoPetkov94 commented
![image](https://github.com/user-attachments/assets/1051fd92-2729-472d-9ab3-e964cd019bad)

2024-08-29 16:41 UTC, HristoPetkov94 commented on lib/screens/home/home_screen.dart
> +  final TextEditingController searchController = TextEditingController();
add dispose method for the controller

2024-08-29 16:49 UTC, HristoPetkov94 commented on lib/screens/home/bloc/home_state.dart
> +enum ViewType { doctors, institutions }
move it to the enum/ package

2024-08-29 16:50 UTC, HristoPetkov94 commented on lib/main.dart
> +          BlocProvider<HomeBloc>(
why did you decided to use the bloc on the main widget instead of in home_screen

2024-08-29 16:54 UTC, HristoPetkov94 commented on lib/routes/app_routes.dart
> +        return MaterialPageRoute(builder: (_) => HomeScreen());
implement listener to listens auth.state from firebase. Based on that to show home_screen or login_screen

2024-08-29 16:55 UTC, HristoPetkov94 commented on lib/routes/app_routes.dart
> +        return MaterialPageRoute(builder: (_) => HomeScreen());
![image](https://github.com/user-attachments/assets/40f8bd7c-ebe9-4e3b-b734-23fcbb9b917f)
for reference

2024-09-01 11:46 UTC, HristoPetkov94 approved these changes

2024-09-01 15:02 UTC, merged