settingsButtonAndScreenImplemented
Cost-Effective-Software-Project-11/gp5 pull request #9
Opened 2024-05-24 06:21 UTC by Jorjo77

2024-05-24 06:34 UTC, HristoPetkov94 requested changes

2024-05-24 06:34 UTC, HristoPetkov94 commented on lib/screens/home/home_screen.dart
> +  //Settings button
these kind of comments are useless.

2024-05-24 06:34 UTC, HristoPetkov94 commented on lib/screens/home/home_screen.dart
> +          fontSize: 20,
since these buttons settings are the same for all buttons, u can extract them into class variable and use them from there to all buttons

2024-05-24 06:35 UTC, HristoPetkov94 approved these changes

2024-05-24 14:34 UTC, VictorAgovski approved these changes

2024-05-25 05:37 UTC, merged

2024-05-25 07:45 UTC, Jorjo77 commented on lib/screens/home/home_screen.dart
> +          fontSize: 20,
ok, I' ll refactore it!